package br.edu.unifei.ecoi09.course.main;

import javax.swing.*;
import java.awt.*;

public class StudentScreen {

    private JPanel studentMainPanel;
    private JPanel studentBottomPanel;
    private JButton backButton;
    private JButton previousButton;
    private JButton nextButton;
    private JPanel studentTopPanel;
    private JPanel studentLeftPanel;
    private JPanel studentRightPanel;
    private JPanel studentCenterPanel;
    private JPanel centerBottomPanel;
    private JPanel centerLeftPanel;
    private JPanel centerRightPanel;


    public JButton getBackButton() {
        return backButton;
    }


    public JButton getPreviousButton() {
        return previousButton;
    }


    public JButton getNextButton() {
        return nextButton;
    }


    public JComboBox getCourseListBox() {
        return courseListBox;
    }

    private JComboBox courseListBox;

    public JButton getRemoveCourseButton() {
        return removeCourseButton;
    }

    public JButton getAddCourseButton() {
        return addCourseButton;
    }

    private JButton removeCourseButton;
    private JButton addCourseButton;
    private JLabel nameLabel;
    private JLabel cpfLabel;
    private JLabel indexLabel;

    public JLabel getBirthdateLabel() {
        return birthdateLabel;
    }

    private JLabel birthdateLabel;

    public JLabel getNameLabel1() {
        return nameLabel1;
    }

    private JLabel nameLabel1;

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JLabel getCpfLabel() {
        return cpfLabel;
    }

    public JLabel getIndexLabel() {
        return indexLabel;
    }

    public JPanel getStudentMainPanel() {
        return studentMainPanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        studentMainPanel = new JPanel();
        studentMainPanel.setLayout(new BorderLayout(0, 0));
        studentBottomPanel = new JPanel();
        studentBottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        studentBottomPanel.setBackground(new Color(-6376005));
        studentMainPanel.add(studentBottomPanel, BorderLayout.SOUTH);
        studentBottomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Options"));
        backButton = new JButton();
        backButton.setText("Back");
        backButton.setMnemonic('B');
        backButton.setDisplayedMnemonicIndex(0);
        studentBottomPanel.add(backButton);
        previousButton = new JButton();
        previousButton.setText("Previous");
        previousButton.setMnemonic('P');
        previousButton.setDisplayedMnemonicIndex(0);
        studentBottomPanel.add(previousButton);
        nextButton = new JButton();
        nextButton.setText("Next");
        nextButton.setMnemonic('N');
        nextButton.setDisplayedMnemonicIndex(0);
        studentBottomPanel.add(nextButton);
        studentTopPanel = new JPanel();
        studentTopPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        studentTopPanel.setBackground(new Color(-6376005));
        studentMainPanel.add(studentTopPanel, BorderLayout.NORTH);
        nameLabel1 = new JLabel();
        nameLabel1.setText("Label");
        studentTopPanel.add(nameLabel1);
        studentCenterPanel = new JPanel();
        studentCenterPanel.setLayout(new BorderLayout(0, 0));
        studentCenterPanel.setBackground(new Color(-6376005));
        studentMainPanel.add(studentCenterPanel, BorderLayout.CENTER);
        centerBottomPanel = new JPanel();
        centerBottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        centerBottomPanel.setBackground(new Color(-6376005));
        studentCenterPanel.add(centerBottomPanel, BorderLayout.SOUTH);
        centerBottomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Courses"));
        final JLabel label1 = new JLabel();
        label1.setText("Course List:");
        centerBottomPanel.add(label1);
        courseListBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        courseListBox.setModel(defaultComboBoxModel1);
        centerBottomPanel.add(courseListBox);
        removeCourseButton = new JButton();
        removeCourseButton.setText("Remove Course");
        removeCourseButton.setMnemonic('R');
        removeCourseButton.setDisplayedMnemonicIndex(0);
        centerBottomPanel.add(removeCourseButton);
        addCourseButton = new JButton();
        addCourseButton.setText("Add Course");
        addCourseButton.setMnemonic('A');
        addCourseButton.setDisplayedMnemonicIndex(0);
        centerBottomPanel.add(addCourseButton);
        centerLeftPanel = new JPanel();
        centerLeftPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        centerLeftPanel.setBackground(new Color(-8997701));
        studentCenterPanel.add(centerLeftPanel, BorderLayout.WEST);
        centerLeftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Information:"));
        final JLabel label2 = new JLabel();
        label2.setText("Name:         ");
        centerLeftPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("CPF:         ");
        centerLeftPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Index:         ");
        centerLeftPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        centerLeftPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 3, false));
        final JLabel label5 = new JLabel();
        label5.setText("Birthdate:         ");
        centerLeftPanel.add(label5, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        centerRightPanel = new JPanel();
        centerRightPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        centerRightPanel.setBackground(new Color(-8997701));
        studentCenterPanel.add(centerRightPanel, BorderLayout.EAST);
        centerRightPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        nameLabel = new JLabel();
        nameLabel.setText("Label");
        centerRightPanel.add(nameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cpfLabel = new JLabel();
        cpfLabel.setText("Label");
        centerRightPanel.add(cpfLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indexLabel = new JLabel();
        indexLabel.setText("Label");
        centerRightPanel.add(indexLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        centerRightPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 3, false));
        birthdateLabel = new JLabel();
        birthdateLabel.setText("Label");
        centerRightPanel.add(birthdateLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return studentMainPanel;
    }
}
