package br.edu.unifei.ecoi09.course.main;

import javax.swing.*;
import java.awt.*;

public class TeacherScreen {

    private JPanel teacherBottomPanel;
    private JButton backButton;
    private JButton previousButton;
    private JButton nextButton;
    private JPanel teacherTopPanel;
    private JPanel teacherLeftPanel;
    private JPanel teacherRightPanel;

    public JPanel getTeacherMainPanel() {
        return teacherMainPanel;
    }

    public JPanel getTeacherBottomPanel() {
        return teacherBottomPanel;
    }

    public void setTeacherBottomPanel(JPanel teacherBottomPanel) {
        this.teacherBottomPanel = teacherBottomPanel;
    }

    public JButton getBackButton() {
        return backButton;
    }

    public void setBackButton(JButton backButton) {
        this.backButton = backButton;
    }

    public JButton getPreviousButton() {
        return previousButton;
    }

    public void setPreviousButton(JButton previousButton) {
        this.previousButton = previousButton;
    }

    public JButton getNextButton() {
        return nextButton;
    }

    public void setNextButton(JButton nextButton) {
        this.nextButton = nextButton;
    }

    public JPanel getTeacherTopPanel() {
        return teacherTopPanel;
    }

    public void setTeacherTopPanel(JPanel teacherTopPanel) {
        this.teacherTopPanel = teacherTopPanel;
    }

    public JPanel getTeacherLeftPanel() {
        return teacherLeftPanel;
    }

    public void setTeacherLeftPanel(JPanel teacherLeftPanel) {
        this.teacherLeftPanel = teacherLeftPanel;
    }

    public JPanel getTeacherRightPanel() {
        return teacherRightPanel;
    }

    public void setTeacherRightPanel(JPanel teacherRightPanel) {
        this.teacherRightPanel = teacherRightPanel;
    }

    public void setTeacherMainPanel(JPanel teacherMainPanel) {
        this.teacherMainPanel = teacherMainPanel;
    }

    private JPanel teacherMainPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        teacherMainPanel = new JPanel();
        teacherMainPanel.setLayout(new BorderLayout(0, 0));
        panel1.add(teacherMainPanel, BorderLayout.CENTER);
        teacherBottomPanel = new JPanel();
        teacherBottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        teacherMainPanel.add(teacherBottomPanel, BorderLayout.SOUTH);
        backButton = new JButton();
        backButton.setText("Back");
        backButton.setMnemonic('B');
        backButton.setDisplayedMnemonicIndex(0);
        teacherBottomPanel.add(backButton);
        previousButton = new JButton();
        previousButton.setText("Previous");
        previousButton.setMnemonic('P');
        previousButton.setDisplayedMnemonicIndex(0);
        teacherBottomPanel.add(previousButton);
        nextButton = new JButton();
        nextButton.setText("Next");
        nextButton.setMnemonic('N');
        nextButton.setDisplayedMnemonicIndex(0);
        teacherBottomPanel.add(nextButton);
        teacherTopPanel = new JPanel();
        teacherTopPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        teacherMainPanel.add(teacherTopPanel, BorderLayout.NORTH);
        teacherLeftPanel = new JPanel();
        teacherLeftPanel.setLayout(new BorderLayout(0, 0));
        teacherMainPanel.add(teacherLeftPanel, BorderLayout.WEST);
        teacherRightPanel = new JPanel();
        teacherRightPanel.setLayout(new BorderLayout(0, 0));
        teacherMainPanel.add(teacherRightPanel, BorderLayout.EAST);
    }
}
